---
services:
  postgres:
    image: postgres:18
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Missing password}
      POSTGRES_USER: ${POSTGRES_USER:?Missing user}
      POSTGRES_DB: ${POSTGRES_DATABASE:?Missing database}
    ports:
      - 5432:5432

  ldap:
    image: ghcr.io/mieweb/ldap-gateway:latest
    env_file: compose.ldap.env
    environment:
      SQL_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}

volumes:
  postgres-data:
